MangoFood.Web/Controllers/AuthController.cs
using MangoFood.Web.Models.DTO;
using MangoFood.Web.Models.DTO.AuthDTO;
using MangoFood.Web.Services.IService;
using MangoFood.Web.Utility;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace MangoFood.Web.Controllers
{
    [Route("Auth/[action]")]
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;

        public AuthController(IAuthService authService,
            ITokenProvider tokenProvider)
        {
            _authService = authService;
            _tokenProvider = tokenProvider;
        }

        [HttpGet]
        public IActionResult Register()
        {
            ViewBag.RoleList = roleList;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterRequestDTO registerRequest)
        {
            if (!ModelState.IsValid)
            {
                return View(registerRequest);
            }

            if (string.IsNullOrEmpty(registerRequest.Role))
            {
                registerRequest.Role = SD.RoleCustomer;
            }

            var response = await _authService.RegisterAsync(registerRequest);
            ResponseDTO? assignRole;

            if (response != null && response.Success)
            {
                assignRole = await _authService.AssignRoleAsync(registerRequest);
                if (assignRole != null && assignRole.Success)
                {
                    TempData["success"] = "Registration is successful";
                    return RedirectToAction(nameof(Login));
                }
            }

            TempData["error"] = response?.Message ?? "Something went wrong";
            ViewBag.RoleList = roleList;
            return View(registerRequest);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDTO loginRequest)
        {
            if (!ModelState.IsValid)
            {
                return View(loginRequest);
            }

            var response = await _authService.LoginAsync(loginRequest);

            if (response != null && response.Success)
            {
                var loginResponse = JsonConvert.DeserializeObject<LoginResponseDTO>(Convert.ToString(response.Result));

                await SignInUser(loginResponse);
                _tokenProvider.SetToken(loginResponse.Token);

                TempData["success"] = "Login is successfull";
                return RedirectToAction("Index", "Home");
            }

            TempData["error"] = response?.Message ?? "Something went wrong";
            return View(loginRequest);
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();

            TempData["success"] = "Log out is successfull";
            return RedirectToAction("Index", "Home");
        }

        private List<SelectListItem> roleList = new List<SelectListItem>()
            {
                new SelectListItem() { Text = SD.RoleCustomer, Value = SD.RoleCustomer},
                new SelectListItem() { Text = SD.RoleAdmin, Value = SD.RoleAdmin }
            };

        private async Task SignInUser(LoginResponseDTO model)
        {
            var handler = new JwtSecurityTokenHandler();

            var jwt = handler.ReadJwtToken(model.Token);
            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));

            identity.AddClaim(new Claim(ClaimTypes.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));

            identity.AddClaim(new Claim(ClaimTypes.Role,
                jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));

            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
        }
    }
}

MangoFood.Web/Controllers/CartController.cs
using MangoFood.Web.Models.DTO;
using MangoFood.Web.Models.DTO.CartDTO;
using MangoFood.Web.Models.DTO.OrderDTO;
using MangoFood.Web.Services.IService;
using MangoFood.Web.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;

namespace MangoFood.Web.Controllers
{
    [Route("[controller]/[action]")]
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IOrderService _orderService;

        public CartController(ICartService cartService, IOrderService orderService)
        {
            _cartService = cartService;
            _orderService = orderService;
        }

        [Authorize]
        public async Task<IActionResult> CartIndex()
        {
            var cart = await RetrieveCartByUserId();
            if(cart.CartDetails != null && cart.CartDetails?.First() != null)
            {
                return View(cart);
            }

            TempData["error"] = "Cart is empty";
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            var cart = await RetrieveCartByUserId();
            if (cart.CartDetails != null && cart.CartDetails?.First() != null)
            {
                return View(cart);
            }

            TempData["error"] = "Something went wrong";
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpPost]
        [ActionName("Checkout")]
        public async Task<IActionResult> Checkout(ShoppingCartDTO cartDTO)
        {
            var cart = await RetrieveCartByUserId();
            cart.CartHeader.Email = cartDTO.CartHeader.Email;
            cart.CartHeader.Phone = cartDTO.CartHeader.Phone;
            cart.CartHeader.FirstName = cartDTO.CartHeader.FirstName;
            cart.CartHeader.LastName = cartDTO.CartHeader.LastName;

            var response = await _orderService.CreateOrder(cart);
            var orderHeader = JsonConvert.DeserializeObject<OrderHeaderDTO>(Convert.ToString(response.Result));

            if(response != null && response.Success)
            {
                var domain = Request.Scheme + "://" + Request.Host + "/";

                StripeRequestDTO stripeRequest = new()
                {
                    ApprovedUrl = domain + "Cart/Confirmation?orderId="+orderHeader.OrderHeaderId,
                    CancelUrl = domain + "Cart/Checkout",
                    OrderHeader = orderHeader
                };

                var stripeResponse = await _orderService.CreateStripeSession(stripeRequest);
                var createdStripe = JsonConvert.DeserializeObject<StripeRequestDTO>(Convert
                    .ToString(stripeResponse.Result));
                
                if(createdStripe == null)
                {
                    TempData["error"] = "Service right now is working incorrectly, sorry";
                    return RedirectToAction("Index", "Home");
                }

                Response.Headers.Add("Location", createdStripe.SessionUrl);
                return new StatusCodeResult(303);
            }

            TempData["error"] = "Cart is empty";
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Confirmation(int orderId)
        {
            var response = await _orderService.ValidateStripeSession(orderId);

            if(response != null && response.Success)
            {
                var orderHeader = JsonConvert.DeserializeObject<OrderHeaderDTO>(Convert.ToString(response.Result));
                if(orderHeader.Status == SD.Status_Approved)
                {
                    return View(orderId);
                }
            }

            TempData["error"] = response?.Message ?? "Something went wrong";
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Remove(int detailID)
        {
            var response = await _cartService.RemoveFromCartAsync(detailID);
            if(response != null && response.Success)
            {
                return RedirectToAction(nameof(CartIndex));
            }

            TempData["erorr"] = response?.Message ?? "Something went wrong";
            return RedirectToAction(nameof(CartIndex));
        }

        [HttpPost]
		public async Task<IActionResult> ApplyCoupon(ShoppingCartDTO cartDTO)
        {
            var response = await _cartService.ApplyCouponToCartCartAsync(cartDTO);
            if(response != null && response.Success)
            {
				return RedirectToAction(nameof(CartIndex));
			}

            TempData["error"] = "Coupon is invalid";
			return RedirectToAction(nameof(CartIndex));
		}

        [HttpPost]
        public async Task<IActionResult> RemoveCoupon(ShoppingCartDTO cartDTO)
        {
            cartDTO.CartHeader.CouponCode = string.Empty;
            var response = await _cartService.ApplyCouponToCartCartAsync(cartDTO);
            if (response != null && response.Success)
            {
                return RedirectToAction(nameof(CartIndex));
            }

            TempData["error"] = "Something went wrong";
            return RedirectToAction(nameof(CartIndex));
        }

        [HttpPost]
        public async Task<IActionResult> EmailCart()
        {
            var cart = await RetrieveCartByUserId();
            cart.CartHeader.Email = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Email)?
                .FirstOrDefault()?.Value;

            var response = await _cartService.EmailCart(cart);
            if (response != null && response.Success)
            {
                TempData["success"] = "Email will be proccessed and sent soon";
                return RedirectToAction(nameof(CartIndex));
            }

            TempData["error"] = "Something went wrong";
            return View(cart);
        }

        private async Task<ShoppingCartDTO?> RetrieveCartByUserId()
        {
            var userId = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
            var response = await _cartService.GetCartByUserIdAsync(userId);
            if(response != null && response.Success)
            {
                return JsonConvert.DeserializeObject<ShoppingCartDTO>(Convert.ToString(response.Result));
            }

            return new ShoppingCartDTO();
        }
    }
}

MangoFood.Web/Controllers/OrderController.cs
using MangoFood.Web.Models.DTO.OrderDTO;
using MangoFood.Web.Services.IService;
using MangoFood.Web.Utility;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;

namespace MangoFood.Web.Controllers
{
    [Route("[controller]/[action]")]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public IActionResult OrderIndex()
        {
            return View();
        }

        [HttpPost("OrderReadyForPickUp")]
        public async Task<IActionResult> OrderReadyForPickUp(int orderId)
        {
            var response = await _orderService.UpdateOrderStatus(orderId, SD.Status_ReadyForPickup);
            if(response != null && response.Success)
            {
                TempData["success"] = "Status updated successfully";
                return RedirectToAction(nameof(OrderIndex));
            }

            TempData["error"] = response?.Message ?? "Something went wrong";
            return View();
        }

        [HttpPost("OrderComplete")]
        public async Task<IActionResult> OrderComplete(int orderId)
        {
            var response = await _orderService.UpdateOrderStatus(orderId, SD.Status_Completed);
            if (response != null && response.Success)
            {
                TempData["success"] = "Status updated successfully";
                return RedirectToAction(nameof(OrderIndex));
            }

            TempData["error"] = response?.Message ?? "Something went wrong";
            return View();
        }

        [HttpPost("OrderCancel")]
        public async Task<IActionResult> OrderCancel(int orderId)
        {
            var response = await _orderService.UpdateOrderStatus(orderId, SD.Status_Cancelled);
            if (response != null && response.Success)
            {
                TempData["success"] = "Status updated successfully";
                return RedirectToAction(nameof(OrderIndex));
            }

            TempData["error"] = response?.Message ?? "Something went wrong";
            return View();
        }

        public async Task<IActionResult> GetOrder(int orderId)
        {
            var order = new OrderHeaderDTO();
            var response = await _orderService.GetOrderById(orderId);

            var userId = User.Claims.Where(c => c.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;

            if (response != null && response.Success)
            {
                order = JsonConvert.DeserializeObject<OrderHeaderDTO>(Convert.ToString(response.Result));
            }
            if(!User.IsInRole(SD.RoleAdmin) && userId != order?.UserId)
            {
                return Forbid("Access Denied");
            }
            return View(order);
        }

        [HttpGet]
        public async Task<IActionResult> GetAll(string status)
        {
            IEnumerable<OrderHeaderDTO> orders = new List<OrderHeaderDTO>();
            string userId = string.Empty;
            if (!User.IsInRole(SD.RoleAdmin))
            {
                userId = User.Claims.Where(c => c.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
            }
            var response = await _orderService.GetOrders(userId);
            if(response != null && response.Success)
            {
                orders = JsonConvert.DeserializeObject<IEnumerable<OrderHeaderDTO>>(Convert.ToString(response.Result));
                switch (status)
                {
                    case "approved":
                        orders = orders.Where(o => o.Status == SD.Status_Approved);
                        break;
                    case "readyforpickup":
                        orders = orders.Where(o => o.Status == SD.Status_ReadyForPickup);
                        break;
                    case "completed":
                        orders = orders.Where(o => o.Status == SD.Status_Completed);
                        break;
                    case "cancelled":
                        orders = orders.Where(o => o.Status == SD.Status_Cancelled);
                        break;
                    default:
                        break;
                }
            }

            return Json(new {data = orders});
        }
    }
}

MangoFood.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MangoFood.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.5/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link rel="stylesheet" href="~/MangoFood.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Mango Food</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupons</a></li>
                                <li><a class="dropdown-item" asp-controller="Product" asp-action="ProductIndex">Products</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="OrderIndex" asp-controller="Order">
                                Manage Order
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="CartIndex" asp-controller="Cart">
                                &nbsp; <i class="bi bi-cart"></i>&nbsp;
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">Hello, @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_NotificationPartial" />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MangoFood.Web - All rights reserved</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/2.0.5/js/dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MangoFood.Web/Views/Shared/_NotificationPartial.cshtml
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script type="text/javascript">
        toastr.error('@TempData["error"]')
        </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}